baseURL = "https://cstate.mnts.studio"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
copyright = "© cState by Mantas Vilčinskas"
pluralizelisttitles = false
buildFuture = true
relativeURLs = true
title = "cState"
[markup]
  [tableOfContents] 
    startLevel = 2 

[taxonomies]
  subtype = "subtype"
  tags = "tags"










# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true
